[2023-02-10T14:58:22.242+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.call_asp_pricing manual__2023-02-10T14:46:10+00:00 [queued]>
[2023-02-10T14:58:22.288+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.call_asp_pricing manual__2023-02-10T14:46:10+00:00 [queued]>
[2023-02-10T14:58:22.291+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T14:58:22.293+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-02-10T14:58:22.295+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T14:58:22.351+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): call_asp_pricing> on 2023-02-10 14:46:10+00:00
[2023-02-10T14:58:40.862+0000] {standard_task_runner.py:55} INFO - Started process 41681 to run task
[2023-02-10T14:58:40.923+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cms_asp_noc', 'call_asp_pricing', 'manual__2023-02-10T14:46:10+00:00', '--job-id', '1686', '--raw', '--subdir', 'DAGS_FOLDER/cms_upd.py', '--cfg-path', '/tmp/tmpadvxpa0d']
[2023-02-10T14:58:44.965+0000] {standard_task_runner.py:83} INFO - Job 1686: Subtask call_asp_pricing
[2023-02-10T14:58:45.450+0000] {task_command.py:388} INFO - Running <TaskInstance: cms_asp_noc.call_asp_pricing manual__2023-02-10T14:46:10+00:00 [running]> on host 2886274f27ea
[2023-02-10T14:58:45.654+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cms_asp_noc
AIRFLOW_CTX_TASK_ID=call_asp_pricing
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T14:46:10+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T14:46:10+00:00
[2023-02-10T14:58:45.680+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cms_pg/call_procedure.py", line 21, in call_procedure
    cur.execute("call sp_upsert_asp_pricing()")
psycopg2.errors.UndefinedTable: relation "cms.ASP Pricing" does not exist
LINE 1: UPDATE cms."ASP Pricing" ASP
               ^
QUERY:  UPDATE cms."ASP Pricing" ASP
		SET "Date_Uploaded" = stg."Date_Uploaded",
			"Short_Description" = stg."Short_Description",
			"HCPCS_Code_Dosage" = stg."HCPCS_Code_Dosage",
			"Payment_Limit" = stg."Payment_Limit",
			"Vaccine_AWP%" = stg."Vaccine_AWP%",
			"Vaccine_Limit" = stg."Vaccine_Limit",
			"Blood_AWP%" = stg."Blood_AWP%",
			"Blood_limit" = stg."Blood_limit",
			"Clotting_Factor" = stg."Clotting_Factor",
			"Notes" = stg."Notes",
			"Date_created"  = stg."Date_created",
			modification_time = stg.modification_time,
			"IsUpdated" = TRUE
		FROM public."ASP Pricing" stg
		where ASP."HCPCS_Code" = stg."HCPCS_Code"
		and ASP.quarter = stg.quarter
CONTEXT:  PL/pgSQL function sp_upsert_asp_pricing() line 6 at SQL statement

[2023-02-10T14:58:47.074+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=cms_asp_noc, task_id=call_asp_pricing, execution_date=20230210T144610, start_date=20230210T145822, end_date=20230210T145847
[2023-02-10T14:58:47.093+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1686 for task call_asp_pricing (relation "cms.ASP Pricing" does not exist
LINE 1: UPDATE cms."ASP Pricing" ASP
               ^
QUERY:  UPDATE cms."ASP Pricing" ASP
		SET "Date_Uploaded" = stg."Date_Uploaded",
			"Short_Description" = stg."Short_Description",
			"HCPCS_Code_Dosage" = stg."HCPCS_Code_Dosage",
			"Payment_Limit" = stg."Payment_Limit",
			"Vaccine_AWP%" = stg."Vaccine_AWP%",
			"Vaccine_Limit" = stg."Vaccine_Limit",
			"Blood_AWP%" = stg."Blood_AWP%",
			"Blood_limit" = stg."Blood_limit",
			"Clotting_Factor" = stg."Clotting_Factor",
			"Notes" = stg."Notes",
			"Date_created"  = stg."Date_created",
			modification_time = stg.modification_time,
			"IsUpdated" = TRUE
		FROM public."ASP Pricing" stg
		where ASP."HCPCS_Code" = stg."HCPCS_Code"
		and ASP.quarter = stg.quarter
CONTEXT:  PL/pgSQL function sp_upsert_asp_pricing() line 6 at SQL statement
; 41681)
[2023-02-10T14:58:47.168+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-10T14:58:47.207+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
