[2023-03-06T16:04:37.947+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.data_load scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2023-03-06T16:04:37.973+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.data_load scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2023-03-06T16:04:37.988+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T16:04:38.001+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-06T16:04:38.013+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T16:04:38.345+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_load> on 2023-03-04 00:00:00+00:00
[2023-03-06T16:04:38.369+0000] {standard_task_runner.py:55} INFO - Started process 211 to run task
[2023-03-06T16:04:38.435+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cms_asp_noc', 'data_load', 'scheduled__2023-03-04T00:00:00+00:00', '--job-id', '1937', '--raw', '--subdir', 'DAGS_FOLDER/cms_upd.py', '--cfg-path', '/tmp/tmpmccq4fqt']
[2023-03-06T16:04:38.472+0000] {standard_task_runner.py:83} INFO - Job 1937: Subtask data_load
[2023-03-06T16:04:40.742+0000] {task_command.py:388} INFO - Running <TaskInstance: cms_asp_noc.data_load scheduled__2023-03-04T00:00:00+00:00 [running]> on host 2886274f27ea
[2023-03-06T16:04:41.148+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cms_asp_noc
AIRFLOW_CTX_TASK_ID=data_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-04T00:00:00+00:00
[2023-03-06T16:04:41.160+0000] {logging_mixin.py:137} INFO - ['section 508 version of April 2022 ASP Pricing File updated 060222.csv', 'section 508 version of April 2022 ASP Pricing File updated 120222.csv', 'section 508 version of COVID_19_NDC_HCPCS_Crosswalk.csv', 'section 508 version of January 2022 ASP Pricing File updated 060222.csv', 'section 508 version of July 2022 ASP NDC-HCPCS Crosswalk 060722.csv', 'section 508 version of July 2022 ASP Pricing File updated 120222.csv', 'section 508 version of July 2022 AWP NDC-HCPCS Crosswalk_060722.csv', 'section 508 version of July 2022 NOC NDC-HCPCS Crosswalk 060722.csv', 'section 508 version of July 2022 NOC Pricing File 060722.csv', 'section 508 version of July 2022 OPPS NDC-HCPCS Crosswalk 060722.csv', 'section 508 version of NDC-HCPCS Crosswalk Introduction Text 060722.csv']
[2023-03-06T16:04:41.168+0000] {logging_mixin.py:137} INFO - /opt/***/op_files/cms_zip_files/section 508 version of April 2022 ASP Pricing File updated 060222.csv
[2023-03-06T16:04:41.212+0000] {logging_mixin.py:137} INFO - success
[2023-03-06T16:04:41.224+0000] {logging_mixin.py:137} INFO - section 508 version of April 2022 ASP Pricing File updated 060222.csv
[2023-03-06T16:04:41.232+0000] {logging_mixin.py:137} INFO - excel file has been cleaned
[2023-03-06T16:04:41.312+0000] {logging_mixin.py:137} INFO -     Date_Uploaded HCPCS_Code  ...    modification_time quarter
0      2023-03-06      90371  ...  2022-06-02 10:10:10       2
1      2023-03-06      90375  ...  2022-06-02 10:10:10       2
2      2023-03-06      90376  ...  2022-06-02 10:10:10       2
3      2023-03-06      90377  ...  2022-06-02 10:10:10       2
4      2023-03-06      90586  ...  2022-06-02 10:10:10       2
..            ...        ...  ...                  ...     ...
641    2023-03-06      Q9965  ...  2022-06-02 10:10:10       2
642    2023-03-06      Q9966  ...  2022-06-02 10:10:10       2
643    2023-03-06      Q9967  ...  2022-06-02 10:10:10       2
644    2023-03-06      Q9991  ...  2022-06-02 10:10:10       2
645    2023-03-06      Q9992  ...  2022-06-02 10:10:10       2

[646 rows x 14 columns]
[2023-03-06T16:04:41.748+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: table "ASP Pricing" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cms_pg/data_load_pg.py", line 112, in data_load_pg
    df.to_sql(table_name, engine_names, if_exists= 'replace', index= False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 860, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1810, in drop_table
    self.get_table(table_name, schema).drop()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 1102, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_ddl
    compiled,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) table "ASP Pricing" does not exist

[SQL: 
DROP TABLE "ASP Pricing"]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-03-06T16:04:41.783+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=cms_asp_noc, task_id=data_load, execution_date=20230304T000000, start_date=20230306T160437, end_date=20230306T160441
[2023-03-06T16:04:41.897+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1937 for task data_load ((psycopg2.errors.UndefinedTable) table "ASP Pricing" does not exist

[SQL: 
DROP TABLE "ASP Pricing"]
(Background on this error at: https://sqlalche.me/e/14/f405); 211)
[2023-03-06T16:04:42.080+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-06T16:04:42.797+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
